// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grcdgtfteagooesjywal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyY2RndGZ0ZWFnb29lc2p5d2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODI4MjAsImV4cCI6MjA1ODk1ODgyMH0.plbjSCZ7pyqYbWBPcJROgDHzQkUAlS8PzQ2TXo15FUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);